In [19]:
import pandas as pd

In [20]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz'

In [21]:
df = pd.read_csv(url)

C:\Users\Manas\AppData\Local\Temp\ipykernel_22676\4176769558.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [22]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [23]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [24]:
len(df)

1369765

In [25]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [26]:
df['VendorID']

0             1
1             1
2             1
3             1
4             2
           ...
1369760    <NA>
1369761    <NA>
1369762    <NA>
1369763    <NA>
1369764    <NA>
Name: VendorID, Length: 1369765, dtype: Int64

In [27]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [28]:
# !uv add sqlalchemy 
# Comment, because
# As, I already installed this library in 1st-time.

In [29]:
import sys
print(sys.executable)

c:\Users\Manas\AppData\Local\Programs\Python\Python311\python.exe

In [30]:
import sqlalchemy # pyright: ignore
sqlalchemy.__version__

'2.0.46'

In [ ]:
# %pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.2.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [42]:
from sqlalchemy import create_engine # pyright: ignore
# engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

password = os.getenv("POSTGRES_PASSWORD")
engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/ny_taxi"
)

with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [ ]:
# df.to_sql(name='yellow_taxi_data', con=engine)
# Don't run it as it will take a long time to run.

In [45]:
df.head(0)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [48]:
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [ ]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [49]:
len(df)

1369765

In [ ]:
df_iter = pd.read_csv( # df_iter => df_iterator
    url, 
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=10000,
)

In [67]:
df = next(df_iter) # Each time next 1000 data-set.
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1000,2,2021-01-01 00:45:42,2021-01-01 00:55:54,1,3.10,1,N,164,263,1,10.5,0.5,0.5,2.86,0.0,0.3,17.16,2.5
1001,2,2021-01-01 00:58:55,2021-01-01 01:09:33,1,2.70,1,N,141,151,1,11.0,0.5,0.5,4.44,0.0,0.3,19.24,2.5
1002,1,2021-01-01 00:19:16,2021-01-01 00:36:58,1,6.90,1,N,161,13,1,22.0,3.0,0.5,0.00,0.0,0.3,25.80,2.5
1003,2,2021-01-01 00:03:18,2021-01-01 00:26:12,1,11.18,1,N,158,169,2,32.0,0.5,0.5,0.00,0.0,0.3,35.80,2.5
1004,1,2021-01-01 00:09:48,2021-01-01 00:28:59,1,7.60,1,N,170,40,2,23.5,3.0,0.5,0.00,0.0,0.3,27.30,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2,2021-01-01 01:39:31,2021-01-01 01:55:07,1,9.55,1,N,193,244,1,27.0,0.5,0.5,6.16,0.0,0.3,36.96,2.5
1996,2,2021-01-01 02:01:46,2021-01-01 02:05:44,1,1.42,1,N,244,152,2,6.0,0.5,0.5,0.00,0.0,0.3,7.30,0.0
1997,2,2021-01-01 00:59:56,2021-01-01 01:13:34,1,3.57,1,N,211,163,1,13.0,0.5,0.5,3.36,0.0,0.3,20.16,2.5
1998,1,2021-01-01 01:08:42,2021-01-01 01:20:47,1,1.80,1,N,41,74,2,9.5,0.5,0.5,0.00,0.0,0.3,10.80,0.0
1999,1,2021-01-01 01:29:30,2021-01-01 01:31:49,1,0.50,1,N,41,41,2,4.0,0.5,0.5,0.00,0.0,0.3,5.30,0.0

In [72]:
%pip install tqdm

Requirement already satisfied: tqdm in c:\users\manas\appdata\local\programs\python\python311\lib\site-packages (4.67.3)
Requirement already satisfied: colorama in c:\users\manas\appdata\roaming\python\python311\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
from tqdm.auto import tqdm # pyright: ignore

In [78]:
for df_chunk in df_iter:
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append',
                    index=False, method="mutli", chunksize=10000)